#!/usr/bin/env ansible-playbook
---
- name: generate all files
  hosts: localhost
  become: no
  gather_facts: yes
  gather_subset:
    - min

  vars_files:
    - vars/main.yml

  tasks:
    - name: set role_path and role_name
      ansible.builtin.set_fact:
        role_path: "{{ lookup('env', 'PWD') }}"
        role_name: "{{ lookup('env', 'PWD') | basename | regex_replace('ansible-role-') }}"

    - name: check meta/main.yml
      stat:
        path: "{{ role_path }}/meta/main.yml"
      register: metamainyml

    - name: load meta/main.yml
      include_vars:
        file: "{{ role_path }}/meta/main.yml"
        name: meta
      when:
        - metamainyml.stat.exists | bool

    - name: check defaults/main.yml
      stat:
        path: "{{ role_path }}/defaults/main.yml"
      register: defaultsmainyml

    - name: load defaults/main.yml
      slurp:
        src: "{{ role_path }}/defaults/main.yml"
      register: variables
      when:
        - defaultsmainyml.stat.exists | bool

    - name: check requirements.yml
      stat:
        path: "{{ role_path }}/requirements.yml"
      register: check_requirements

    - name: load requirements.yml
      include_vars:
        file: "{{ role_path }}/requirements.yml"
        name: requirements
      when:
        - check_requirements.stat.exists | bool

    - name: check requirements.txt
      stat:
        path: "{{ role_path }}/requirements.yml"
      register: check_requirements_pip

    - name: check molecule/config.yml
      stat:
        path: "{{ role_path }}/molecule/config.yml"
      register: moleculeconfigyml

    - name: load molecule/config.yml
      include_vars:
        file: "{{ role_path }}/molecule/config.yml"
        name: molecule_config
      when:
        - moleculeconfigyml.stat.exists | bool

    - name: load molecule/default/converge.yml
      slurp:
        src: "{{ role_path }}/molecule/default/converge.yml"
      register: example

    - name: check molecule/default/prepare.yml
      stat:
        path: "{{ role_path }}/molecule/default/prepare.yml"
      register: check_prepare

    - name: load molecule/default/prepare.yml
      slurp:
        src: "{{ role_path }}/molecule/default/prepare.yml"
      register: prepare
      when:
        - check_prepare.stat.exists | bool

    - name: check molecule/default/verify.yml
      stat:
        path: "{{ role_path }}/molecule/default/verify.yml"
      register: verify

    - name: load molecule/default/verify.yml
      slurp:
        src: "{{ role_path }}/molecule/default/verify.yml"
      register: verifyyml
      when:
        - verify.stat.exists | bool

    - name: check molecule/default/defaults.yml
      stat:
        path: "{{ role_path }}/molecule/default/defaults.yml"
      register: defaults

    - name: create .github directories
      file:
        path: "{{ role_path }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - ".github"
        - ".github/workflows"
        - ".github/ISSUE_TEMPLATE"

    - name: render files
      template:
        src: "{{ playbook_dir }}/templates/{{ item.source }}.j2"
        dest: "{{ role_path }}/{{ item.dest | default (item.source) }}"
        mode: "0644"
      with_items:
        - source: ".ansible-lint"
        - source: ".yamllint"
        - source: ".gitignore"
        - source: ".github/ISSUE_TEMPLATE/feature_request.md"
        - source: "LICENSE"
        # - source: "SECURITY.md"
        - source: "README.md"
        #- source: ".github/workflows/molecule.yml"
        - source: ".github/workflows/galaxy.yml"
        - source: ".gitlab-ci.yml"
      loop_control:
        label: "{{ item.source }}"

    - name: Find old workflows to delete
      find:
        paths: "{{ role_path }}/.github/workflows/"
        patterns: "molecule_*.yml"
      register: workflows_delete

    - name: delete old workflows
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ workflows_delete.files }}"

    - name: generate workflow
      template:
        src: "{{ playbook_dir }}/templates/.github/workflows/molecule.yml.j2"
        dest: "{{ role_path }}/.github/workflows/molecule.yml"
        mode: "0644"
